import type { House, Resident, Post } from "./types";

// ── Houses ──────────────────────────────────────────────────────────
export const houses: House[] = [
  {
    id: "h1",
    name: "성수 로움",
    city: "서울",
    neighborhood: "성수동",
    region: "성수동",
    lat: 37.5446,
    lng: 127.0559,
    monthlyRent: 780000,
    deposit: 3000000,
    cleaningFee: 80000,
    maintenanceFee: 40000,
    roomType: "one_room",
    bedrooms: 6,
    residents: 5,
    capacity: 6,
    amenities: ["루프탑", "코워킹 공간", "세탁실", "초고속 와이파이", "주 1회 청소"],
    vibe: ["creative", "social"],
    rating: 4.9,
    reviews: 132,
    color: "#FF7A5C",
    photo: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&auto=format&fit=crop",
    blurb: "성수동 작업실 감성을 살린 공유주거로, 넓은 공용 공간과 편리한 교통을 함께 누릴 수 있습니다.",
    availableFrom: "2026-07-15",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h2",
    name: "연남 고요한 집",
    city: "서울",
    neighborhood: "연남동",
    region: "연남동",
    lat: 37.5636,
    lng: 126.9256,
    monthlyRent: 690000,
    deposit: 2500000,
    cleaningFee: 70000,
    maintenanceFee: 70000,
    roomType: "one_room",
    bedrooms: 5,
    residents: 4,
    capacity: 5,
    amenities: ["정원", "독서 공간", "세탁실", "초고속 와이파이", "자전거 보관소"],
    vibe: ["quiet", "calm"],
    rating: 4.8,
    reviews: 96,
    color: "#00A699",
    photo: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&auto=format&fit=crop",
    blurb: "연남동 골목의 차분한 분위기를 담은 공유주거로, 조용한 생활과 산책을 선호하는 분께 잘 맞습니다.",
    availableFrom: "2026-08-01",
    minStayMonths: 6,
    genderPolicy: "female_only",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h3",
    name: "망원 리버 스튜디오",
    city: "서울",
    neighborhood: "망원동",
    region: "망원동",
    lat: 37.5559,
    lng: 126.9016,
    monthlyRent: 950000,
    deposit: 4000000,
    cleaningFee: 100000,
    maintenanceFee: 50000,
    roomType: "apartment",
    bedrooms: 8,
    residents: 6,
    capacity: 8,
    amenities: ["개별 욕실", "운동 공간", "루프탑", "초고속 와이파이", "무인 택배함"],
    vibe: ["independent", "social"],
    rating: 4.7,
    reviews: 210,
    color: "#3E9BC4",
    photo: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    blurb: "한강과 망원시장이 가까운 스튜디오형 주거로, 독립적인 공간과 편리한 생활 인프라를 제공합니다.",
    availableFrom: "2026-07-08",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h4",
    name: "해방촌 테라스",
    city: "서울",
    neighborhood: "용산구",
    region: "용산구",
    lat: 37.5405,
    lng: 126.9895,
    monthlyRent: 620000,
    deposit: 2000000,
    cleaningFee: 60000,
    maintenanceFee: 70000,
    roomType: "share_room",
    bedrooms: 4,
    residents: 6,
    capacity: 8,
    amenities: ["테라스", "공동 저녁 식사", "세탁실", "초고속 와이파이"],
    vibe: ["social", "international"],
    rating: 4.6,
    reviews: 178,
    color: "#FF5A5F",
    photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&auto=format&fit=crop",
    blurb: "해방촌의 개성 있는 생활권과 넓은 테라스를 갖춘 사교적인 공유주거입니다.",
    availableFrom: "2026-07-20",
    minStayMonths: 2,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: true,
    parking: false,
  },
  {
    id: "h5",
    name: "홍대 메이커 하우스",
    city: "서울",
    neighborhood: "서교동",
    region: "서교동",
    lat: 37.5546,
    lng: 126.9226,
    monthlyRent: 720000,
    deposit: 2800000,
    cleaningFee: 70000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 6,
    residents: 6,
    capacity: 6,
    amenities: ["작업실", "3D 프린터", "코워킹 공간", "초고속 와이파이", "세탁실"],
    vibe: ["creative", "focused"],
    rating: 4.8,
    reviews: 145,
    color: "#7C6FE0",
    photo: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop",
    blurb: "창작자와 직장인이 함께 생활할 수 있도록 작업 공간과 공용 주방을 갖춘 주거입니다.",
    availableFrom: "2026-09-01",
    minStayMonths: 6,
    genderPolicy: "male_only",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h7",
    name: "서초 출퇴근 하우스",
    city: "서울",
    neighborhood: "서초구",
    region: "서초구",
    lat: 37.4837,
    lng: 127.0324,
    monthlyRent: 880000,
    deposit: 3500000,
    cleaningFee: 90000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 6,
    residents: 5,
    capacity: 6,
    amenities: ["코워킹 공간", "운동 공간", "세탁실", "초고속 와이파이", "무인 택배함"],
    vibe: ["quiet", "focused"],
    rating: 4.7,
    reviews: 74,
    color: "#4A8FD6",
    photo: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80&auto=format&fit=crop",
    blurb: "강남권 출퇴근이 편리하고 조용한 생활 환경을 갖춘 직장인 중심 공유주거입니다.",
    availableFrom: "2026-07-18",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h8",
    name: "판교 밸리 하우스",
    city: "성남",
    neighborhood: "분당구",
    region: "분당구",
    lat: 37.3925,
    lng: 127.1180,
    monthlyRent: 810000,
    deposit: 3000000,
    cleaningFee: 80000,
    maintenanceFee: 40000,
    roomType: "apartment",
    bedrooms: 7,
    residents: 6,
    capacity: 7,
    amenities: ["개별 욕실", "코워킹 공간", "운동 공간", "초고속 와이파이", "주 1회 청소"],
    vibe: ["focused", "social"],
    rating: 4.8,
    reviews: 61,
    color: "#2FB39C",
    photo: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80&auto=format&fit=crop",
    blurb: "판교 업무지구와 가까우며 업무와 휴식을 균형 있게 누릴 수 있는 쾌적한 주거입니다.",
    availableFrom: "2026-08-05",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: true,
    parking: true,
  },
  {
    id: "h6",
    name: "뚝섬 선라이즈",
    city: "서울",
    neighborhood: "성동구",
    region: "성동구",
    lat: 37.5310,
    lng: 127.0668,
    monthlyRent: 840000,
    deposit: 3200000,
    cleaningFee: 80000,
    maintenanceFee: 40000,
    roomType: "one_room",
    bedrooms: 7,
    residents: 5,
    capacity: 7,
    amenities: ["River view", "Yoga room", "루프탑", "초고속 와이파이", "주 1회 청소"],
    vibe: ["calm", "wellness"],
    rating: 4.9,
    reviews: 88,
    color: "#FFB400",
    photo: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80&auto=format&fit=crop",
    blurb: "서울숲과 뚝섬한강공원이 가까워 여가와 출퇴근을 함께 고려할 수 있는 공유주거입니다.",
    availableFrom: "2026-08-12",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h9",
    name: "스튜디오 하우스",
    city: "서울",
    neighborhood: "성동구",
    region: "성동구",
    lat: 37.5364,
    lng: 127.0655,
    monthlyRent: 600000,
    deposit: 2600000,
    cleaningFee: 60000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 5,
    residents: 3,
    capacity: 4,
    amenities: ['Rooftop', 'Parcel locker', 'Fiber wifi', 'Workshop', 'Coworking room', 'Garden'],
    vibe: ['focused', 'quiet'],
    rating: 4.5,
    reviews: 181,
    color: "#3AA6B9",
    photo: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-07-08",
    minStayMonths: 6,
    genderPolicy: "male_only",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h10",
    name: "성수 시더 플랫",
    city: "서울",
    neighborhood: "성수동",
    region: "성수동",
    lat: 37.5453,
    lng: 127.0515,
    monthlyRent: 650000,
    deposit: 2500000,
    cleaningFee: 60000,
    maintenanceFee: 50000,
    roomType: "apartment",
    bedrooms: 5,
    residents: 4,
    capacity: 8,
    amenities: ['Reading nook', 'Laundry', 'Coworking room', 'Ensuite', 'Fiber wifi', 'Gym'],
    vibe: ['social', 'wellness'],
    rating: 4.8,
    reviews: 184,
    color: "#FF7A5C",
    photo: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-11-14",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h11",
    name: "스튜디오 하우스",
    city: "서울",
    neighborhood: "홍대",
    region: "홍대",
    lat: 37.5530,
    lng: 126.9270,
    monthlyRent: 920000,
    deposit: 3300000,
    cleaningFee: 90000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 6,
    residents: 4,
    capacity: 7,
    amenities: ['Bike storage', 'Weekly cleaning', 'Ensuite', 'Coworking room', 'Reading nook', 'Garden'],
    vibe: ['creative', 'focused'],
    rating: 4.6,
    reviews: 165,
    color: "#00A699",
    photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-07-25",
    minStayMonths: 6,
    genderPolicy: "male_only",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h12",
    name: "커먼즈 룸",
    city: "서울",
    neighborhood: "강남구",
    region: "강남구",
    lat: 37.5172,
    lng: 127.0509,
    monthlyRent: 610000,
    deposit: 2700000,
    cleaningFee: 60000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 7,
    residents: 7,
    capacity: 7,
    amenities: ['Coworking room', 'Rooftop', 'Weekly cleaning', 'Ensuite', 'Bike storage', 'Reading nook'],
    vibe: ['focused', 'international'],
    rating: 4.6,
    reviews: 158,
    color: "#3E9BC4",
    photo: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-07-16",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h13",
    name: "네스트 플랫",
    city: "서울",
    neighborhood: "서초구",
    region: "서초구",
    lat: 37.4887,
    lng: 127.0324,
    monthlyRent: 840000,
    deposit: 3100000,
    cleaningFee: 80000,
    maintenanceFee: 50000,
    roomType: "share_room",
    bedrooms: 8,
    residents: 3,
    capacity: 6,
    amenities: ['Parcel locker', 'Weekly cleaning', 'Garden', 'Gym', 'Reading nook'],
    vibe: ['calm', 'social'],
    rating: 4.4,
    reviews: 78,
    color: "#FF5A5F",
    photo: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-10-27",
    minStayMonths: 2,
    genderPolicy: "male_only",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h14",
    name: "헤이븐 하우스",
    city: "서울",
    neighborhood: "성동구",
    region: "성동구",
    lat: 37.5323,
    lng: 127.0646,
    monthlyRent: 1000000,
    deposit: 4300000,
    cleaningFee: 100000,
    maintenanceFee: 50000,
    roomType: "share_room",
    bedrooms: 4,
    residents: 7,
    capacity: 8,
    amenities: ['Yoga room', 'Rooftop', 'Bike storage', 'Parcel locker', 'Garden', 'Ensuite'],
    vibe: ['focused', 'calm'],
    rating: 4.5,
    reviews: 202,
    color: "#7C6FE0",
    photo: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-07-07",
    minStayMonths: 2,
    genderPolicy: "female_only",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h15",
    name: "블룸 홈",
    city: "서울",
    neighborhood: "강남구",
    region: "강남구",
    lat: 37.5130,
    lng: 127.0425,
    monthlyRent: 950000,
    deposit: 3100000,
    cleaningFee: 100000,
    maintenanceFee: 60000,
    roomType: "whole_house",
    bedrooms: 5,
    residents: 5,
    capacity: 5,
    amenities: ['Reading nook', 'Weekly cleaning', 'Gym', 'Ensuite'],
    vibe: ['international', 'calm'],
    rating: 4.5,
    reviews: 164,
    color: "#FFB400",
    photo: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-09-03",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h16",
    name: "아틀리에 플랫",
    city: "서울",
    neighborhood: "마포구",
    region: "마포구",
    lat: 37.5606,
    lng: 126.9073,
    monthlyRent: 650000,
    deposit: 2700000,
    cleaningFee: 60000,
    maintenanceFee: 40000,
    roomType: "whole_house",
    bedrooms: 8,
    residents: 4,
    capacity: 4,
    amenities: ['Reading nook', 'Coworking room', 'Weekly cleaning', 'Parcel locker', 'Gym'],
    vibe: ['creative', 'independent'],
    rating: 4.8,
    reviews: 176,
    color: "#4A8FD6",
    photo: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-08-26",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h17",
    name: "아틀리에 플랫",
    city: "서울",
    neighborhood: "분당구",
    region: "분당구",
    lat: 37.3908,
    lng: 127.1123,
    monthlyRent: 730000,
    deposit: 2800000,
    cleaningFee: 70000,
    maintenanceFee: 60000,
    roomType: "one_room",
    bedrooms: 4,
    residents: 4,
    capacity: 5,
    amenities: ['Workshop', 'Yoga room', 'Gym', 'Reading nook', 'Coworking room'],
    vibe: ['calm', 'quiet'],
    rating: 4.5,
    reviews: 90,
    color: "#2FB39C",
    photo: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-11-20",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h18",
    name: "메이플 룸",
    city: "서울",
    neighborhood: "이태원",
    region: "이태원",
    lat: 37.5363,
    lng: 126.9995,
    monthlyRent: 860000,
    deposit: 3700000,
    cleaningFee: 90000,
    maintenanceFee: 60000,
    roomType: "share_room",
    bedrooms: 6,
    residents: 7,
    capacity: 7,
    amenities: ['Coworking room', 'Yoga room', 'Garden', 'Bike storage', 'Reading nook'],
    vibe: ['social', 'international'],
    rating: 4.5,
    reviews: 72,
    color: "#E8654F",
    photo: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-10-26",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h19",
    name: "아틀리에 코리빙",
    city: "서울",
    neighborhood: "망원동",
    region: "망원동",
    lat: 37.5565,
    lng: 126.8972,
    monthlyRent: 1020000,
    deposit: 4100000,
    cleaningFee: 100000,
    maintenanceFee: 70000,
    roomType: "one_room",
    bedrooms: 8,
    residents: 7,
    capacity: 8,
    amenities: ['Garden', 'Fiber wifi', 'Yoga room', 'Rooftop'],
    vibe: ['wellness', 'social'],
    rating: 4.6,
    reviews: 101,
    color: "#3AA6B9",
    photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-10-27",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h20",
    name: "하버 하우스",
    city: "서울",
    neighborhood: "이태원",
    region: "이태원",
    lat: 37.5393,
    lng: 126.9936,
    monthlyRent: 900000,
    deposit: 3100000,
    cleaningFee: 90000,
    maintenanceFee: 40000,
    roomType: "share_room",
    bedrooms: 4,
    residents: 2,
    capacity: 8,
    amenities: ['Workshop', 'Laundry', 'Ensuite', 'Rooftop', 'Yoga room'],
    vibe: ['creative', 'social'],
    rating: 4.7,
    reviews: 225,
    color: "#FF7A5C",
    photo: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-11-17",
    minStayMonths: 3,
    genderPolicy: "male_only",
    petsAllowed: false,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h21",
    name: "쿼터 플랫",
    city: "서울",
    neighborhood: "용산구",
    region: "용산구",
    lat: 37.5368,
    lng: 126.9840,
    monthlyRent: 880000,
    deposit: 3300000,
    cleaningFee: 90000,
    maintenanceFee: 70000,
    roomType: "one_room",
    bedrooms: 7,
    residents: 2,
    capacity: 4,
    amenities: ['Gym', 'Ensuite', 'Parcel locker', 'Yoga room', 'Reading nook'],
    vibe: ['calm', 'international'],
    rating: 4.6,
    reviews: 170,
    color: "#00A699",
    photo: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-11-09",
    minStayMonths: 6,
    genderPolicy: "male_only",
    petsAllowed: false,
    smokingAllowed: true,
    parking: true,
  },
  {
    id: "h22",
    name: "네스트 레지던스",
    city: "서울",
    neighborhood: "연남동",
    region: "연남동",
    lat: 37.5623,
    lng: 126.9234,
    monthlyRent: 830000,
    deposit: 2700000,
    cleaningFee: 80000,
    maintenanceFee: 50000,
    roomType: "share_room",
    bedrooms: 6,
    residents: 6,
    capacity: 9,
    amenities: ['Workshop', 'Laundry', 'Reading nook', 'Gym'],
    vibe: ['creative', 'independent'],
    rating: 4.9,
    reviews: 159,
    color: "#3E9BC4",
    photo: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-10-06",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h23",
    name: "윌로우 코리빙",
    city: "서울",
    neighborhood: "서초구",
    region: "서초구",
    lat: 37.4800,
    lng: 127.0302,
    monthlyRent: 570000,
    deposit: 2100000,
    cleaningFee: 60000,
    maintenanceFee: 50000,
    roomType: "whole_house",
    bedrooms: 6,
    residents: 5,
    capacity: 7,
    amenities: ['Rooftop', 'Garden', 'Gym', 'Parcel locker', 'Weekly cleaning', 'Coworking room'],
    vibe: ['social', 'focused'],
    rating: 4.5,
    reviews: 66,
    color: "#FF5A5F",
    photo: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-07-25",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: true,
    parking: true,
  },
  {
    id: "h24",
    name: "윌로우 코리빙",
    city: "서울",
    neighborhood: "서초구",
    region: "서초구",
    lat: 37.4795,
    lng: 127.0374,
    monthlyRent: 1000000,
    deposit: 3600000,
    cleaningFee: 100000,
    maintenanceFee: 40000,
    roomType: "apartment",
    bedrooms: 8,
    residents: 2,
    capacity: 6,
    amenities: ['Laundry', 'Garden', 'Coworking room', 'Weekly cleaning', 'Rooftop', 'Reading nook'],
    vibe: ['wellness', 'quiet'],
    rating: 4.7,
    reviews: 96,
    color: "#7C6FE0",
    photo: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-10-01",
    minStayMonths: 2,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h25",
    name: "커먼즈 하우스",
    city: "서울",
    neighborhood: "망원동",
    region: "망원동",
    lat: 37.5504,
    lng: 126.9041,
    monthlyRent: 660000,
    deposit: 2300000,
    cleaningFee: 70000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 7,
    residents: 3,
    capacity: 5,
    amenities: ['Reading nook', 'Weekly cleaning', 'Parcel locker', 'Fiber wifi', 'Yoga room'],
    vibe: ['independent', 'wellness'],
    rating: 4.8,
    reviews: 109,
    color: "#FFB400",
    photo: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-07-01",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h26",
    name: "선룸 하우스",
    city: "서울",
    neighborhood: "용산구",
    region: "용산구",
    lat: 37.5457,
    lng: 126.9848,
    monthlyRent: 980000,
    deposit: 3800000,
    cleaningFee: 100000,
    maintenanceFee: 50000,
    roomType: "apartment",
    bedrooms: 8,
    residents: 6,
    capacity: 7,
    amenities: ['Yoga room', 'Fiber wifi', 'Workshop', 'Gym', 'Reading nook'],
    vibe: ['creative', 'calm'],
    rating: 4.9,
    reviews: 53,
    color: "#4A8FD6",
    photo: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-09-14",
    minStayMonths: 2,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h27",
    name: "로프트 플레이스",
    city: "서울",
    neighborhood: "종로구",
    region: "종로구",
    lat: 37.5786,
    lng: 126.9806,
    monthlyRent: 580000,
    deposit: 2200000,
    cleaningFee: 60000,
    maintenanceFee: 40000,
    roomType: "whole_house",
    bedrooms: 5,
    residents: 4,
    capacity: 5,
    amenities: ['Rooftop', 'Weekly cleaning', 'Gym', 'Reading nook', 'Parcel locker'],
    vibe: ['international', 'social'],
    rating: 4.4,
    reviews: 119,
    color: "#2FB39C",
    photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-07-11",
    minStayMonths: 2,
    genderPolicy: "female_only",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h28",
    name: "헤이븐 플레이스",
    city: "서울",
    neighborhood: "마포구",
    region: "마포구",
    lat: 37.5696,
    lng: 126.8970,
    monthlyRent: 650000,
    deposit: 2400000,
    cleaningFee: 60000,
    maintenanceFee: 40000,
    roomType: "one_room",
    bedrooms: 8,
    residents: 3,
    capacity: 4,
    amenities: ['Weekly cleaning', 'Workshop', 'Reading nook', 'Fiber wifi'],
    vibe: ['social', 'wellness'],
    rating: 4.9,
    reviews: 79,
    color: "#E8654F",
    photo: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-10-05",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h29",
    name: "커먼즈 레지던스",
    city: "서울",
    neighborhood: "종로구",
    region: "종로구",
    lat: 37.5721,
    lng: 126.9818,
    monthlyRent: 890000,
    deposit: 3700000,
    cleaningFee: 90000,
    maintenanceFee: 50000,
    roomType: "share_room",
    bedrooms: 7,
    residents: 8,
    capacity: 8,
    amenities: ['Reading nook', 'Ensuite', 'Workshop', 'Fiber wifi'],
    vibe: ['social', 'quiet'],
    rating: 4.4,
    reviews: 203,
    color: "#3AA6B9",
    photo: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-10-18",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h30",
    name: "쿼터 스튜디오",
    city: "서울",
    neighborhood: "서교동",
    region: "서교동",
    lat: 37.5486,
    lng: 126.9262,
    monthlyRent: 980000,
    deposit: 3800000,
    cleaningFee: 100000,
    maintenanceFee: 70000,
    roomType: "one_room",
    bedrooms: 4,
    residents: 9,
    capacity: 9,
    amenities: ['Workshop', 'Coworking room', 'Weekly cleaning', 'Fiber wifi', 'Ensuite'],
    vibe: ['calm', 'international'],
    rating: 4.8,
    reviews: 157,
    color: "#FF7A5C",
    photo: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-10-22",
    minStayMonths: 2,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h31",
    name: "가든 홈",
    city: "서울",
    neighborhood: "강남구",
    region: "강남구",
    lat: 37.5130,
    lng: 127.0443,
    monthlyRent: 950000,
    deposit: 3700000,
    cleaningFee: 100000,
    maintenanceFee: 60000,
    roomType: "whole_house",
    bedrooms: 4,
    residents: 3,
    capacity: 4,
    amenities: ['Bike storage', 'Weekly cleaning', 'Reading nook', 'Coworking room'],
    vibe: ['calm', 'international'],
    rating: 4.7,
    reviews: 221,
    color: "#00A699",
    photo: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-10-25",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h32",
    name: "쿼터 홈",
    city: "서울",
    neighborhood: "분당구",
    region: "분당구",
    lat: 37.3867,
    lng: 127.1175,
    monthlyRent: 730000,
    deposit: 2700000,
    cleaningFee: 70000,
    maintenanceFee: 50000,
    roomType: "apartment",
    bedrooms: 5,
    residents: 2,
    capacity: 5,
    amenities: ['Coworking room', 'Laundry', 'Parcel locker', 'Weekly cleaning', 'Gym', 'Yoga room'],
    vibe: ['wellness', 'quiet'],
    rating: 4.8,
    reviews: 99,
    color: "#3E9BC4",
    photo: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-07-06",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h33",
    name: "윌로우 플레이스",
    city: "서울",
    neighborhood: "서초구",
    region: "서초구",
    lat: 37.4818,
    lng: 127.0302,
    monthlyRent: 560000,
    deposit: 2000000,
    cleaningFee: 60000,
    maintenanceFee: 40000,
    roomType: "whole_house",
    bedrooms: 5,
    residents: 5,
    capacity: 6,
    amenities: ['Fiber wifi', 'Yoga room', 'Rooftop', 'Weekly cleaning'],
    vibe: ['wellness', 'creative'],
    rating: 4.4,
    reviews: 139,
    color: "#FF5A5F",
    photo: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-09-28",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: true,
    parking: false,
  },
  {
    id: "h34",
    name: "가든 홈",
    city: "서울",
    neighborhood: "용산구",
    region: "용산구",
    lat: 37.5462,
    lng: 126.9887,
    monthlyRent: 680000,
    deposit: 2900000,
    cleaningFee: 70000,
    maintenanceFee: 70000,
    roomType: "whole_house",
    bedrooms: 6,
    residents: 2,
    capacity: 7,
    amenities: ['Garden', 'Parcel locker', 'Yoga room', 'Fiber wifi', 'Coworking room', 'Rooftop'],
    vibe: ['focused', 'calm'],
    rating: 4.7,
    reviews: 75,
    color: "#7C6FE0",
    photo: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-11-05",
    minStayMonths: 2,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h35",
    name: "스튜디오 룸",
    city: "서울",
    neighborhood: "서초구",
    region: "서초구",
    lat: 37.4856,
    lng: 127.0300,
    monthlyRent: 630000,
    deposit: 2200000,
    cleaningFee: 60000,
    maintenanceFee: 50000,
    roomType: "apartment",
    bedrooms: 6,
    residents: 2,
    capacity: 5,
    amenities: ['Parcel locker', 'Bike storage', 'Workshop', 'Fiber wifi'],
    vibe: ['independent', 'creative'],
    rating: 4.9,
    reviews: 155,
    color: "#FFB400",
    photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-08-08",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h36",
    name: "선룸 플랫",
    city: "서울",
    neighborhood: "서교동",
    region: "서교동",
    lat: 37.5583,
    lng: 126.9190,
    monthlyRent: 1030000,
    deposit: 4500000,
    cleaningFee: 100000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 4,
    residents: 5,
    capacity: 7,
    amenities: ['Parcel locker', 'Fiber wifi', 'Garden', 'Weekly cleaning', 'Gym', 'Rooftop'],
    vibe: ['independent', 'creative'],
    rating: 4.7,
    reviews: 132,
    color: "#4A8FD6",
    photo: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop",
    blurb: "밝은 공용 공간과 편리한 교통을 갖춘 서울의 공유주거입니다. 생활 성향이 비슷한 입주자들과 편안한 일상을 시작해보세요.",
    availableFrom: "2026-09-08",
    minStayMonths: 2,
    genderPolicy: "female_only",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  }

];

// Demo-only classification so the three-axis filters and seat booking can be
// exercised even when NEXT_PUBLIC_USE_REAL_API is false. Production Room rows
// are migrated conservatively and ambiguous legacy values remain review-required.
for (const house of houses) {
  if (house.roomType === "whole_house") {
    house.rentalUnit = "whole";
    house.buildingType = "house";
    house.sharedFacilities = [];
  } else if (house.roomType === "share_room") {
    house.rentalUnit = "bed";
    house.buildingType = "house";
    house.sharedFacilities = ["bathroom", "kitchen", "living_room", "laundry_room"];
  } else if (house.roomType === "apartment") {
    house.rentalUnit = "private_room";
    house.buildingType = "apartment";
    house.sharedFacilities = ["bathroom", "kitchen", "living_room", "laundry_room"];
  } else {
    house.rentalUnit = "private_room";
    house.buildingType = "studio";
    house.sharedFacilities = ["bathroom", "kitchen", "laundry_room"];
  }
  house.classificationReviewRequired = false;
}

// ── Residents (used for matching) ───────────────────────────────────
export const residents: Resident[] = [
  {
    id: "r1",
    name: "재이",
    age: 27,
    occupation: "UX Designer",
    bio: "아침형 생활을 하며 정리정돈을 중요하게 생각하고, 조용한 일요일을 좋아합니다.",
    sleepSchedule: "early",
    cleanliness: 5,
    social: 3,
    interests: ["디자인", "커피", "hiking", "film"],
    smoker: false,
    pets: false,
  },
  {
    id: "r2",
    name: "민아",
    age: 24,
    occupation: "Illustrator",
    bio: "Night owl, always mid-project, will feed anyone's plants.",
    sleepSchedule: "night",
    cleanliness: 3,
    social: 5,
    interests: ["예술", "음악", "요리", "film"],
    smoker: false,
    pets: true,
  },
  {
    id: "r3",
    name: "토마스",
    age: 31,
    occupation: "Backend Engineer",
    bio: "근무 시간이 유연하고 한적한 시간에 운동하며, 조용하지만 친근한 성격입니다.",
    sleepSchedule: "flexible",
    cleanliness: 4,
    social: 2,
    interests: ["coding", "climbing", "커피", "games"],
    smoker: false,
    pets: false,
  },
  {
    id: "r4",
    name: "수",
    age: 29,
    occupation: "Chef",
    bio: "Cooks big shared dinners, hums in the kitchen, up late.",
    sleepSchedule: "night",
    cleanliness: 4,
    social: 5,
    interests: ["요리", "음악", "여행", "wine"],
    smoker: false,
    pets: false,
  },
  {
    id: "r5",
    name: "하나",
    age: 26,
    occupation: "PhD Student",
    bio: "Reads a lot, needs calm, joins the occasional board game night.",
    sleepSchedule: "early",
    cleanliness: 5,
    social: 2,
    interests: ["books", "hiking", "games", "커피"],
    smoker: false,
    pets: false,
  },
  {
    id: "r6",
    name: "디에고",
    age: 33,
    occupation: "Product Manager",
    bio: "Social connector, hosts the house dinners, keeps the calendar.",
    sleepSchedule: "flexible",
    cleanliness: 3,
    social: 5,
    interests: ["여행", "음악", "요리", "운동"],
    smoker: false,
    pets: true,
  },
];

// ── Community posts ─────────────────────────────────────────────────
export const posts: Post[] = [
  {
    id: "p1",
    houseId: "h1",
    author: "디에고",
    category: "event",
    title: "이번 주 금요일 오후 8시 루프탑 저녁 모임",
    body: "카레를 넉넉히 준비할 예정입니다. 간단한 음식이나 음료를 가져오셔도 좋고, 편하게 참석만 하셔도 됩니다. 냉장고 옆 신청표에 이름을 적어주세요.",
    createdAt: "2026-07-01T09:00:00Z",
    replies: 7,
    pinned: true,
  },
  {
    id: "p2",
    houseId: "h1",
    author: "재이",
    category: "chore",
    title: "7월 주방 대청소 순번 안내",
    body: "청소 순번을 새로 정리했습니다. 함께 담당하는 입주자를 확인하고, 이번 달에는 조리대를 항상 깔끔하게 유지해주세요.",
    createdAt: "2026-07-01T11:30:00Z",
    replies: 3,
    pinned: false,
  },
  {
    id: "p3",
    houseId: "h1",
    author: "민아",
    category: "market",
    title: "무료 나눔: 스탠드와 의자 두 개",
    body: "방 배치를 바꾸면서 사용하지 않는 물건을 나눔합니다. 코워킹 공간 옆에 두었으며 먼저 가져가시는 분께 드립니다.",
    createdAt: "2026-06-30T18:20:00Z",
    replies: 2,
    pinned: false,
  },
  {
    id: "p4",
    houseId: "h1",
    author: "하우스 매니저",
    category: "notice",
    title: "화요일 오후 2~4시 단수 안내",
    body: "화요일 오후 두 시간 동안 건물 수도 점검으로 물 사용이 어렵습니다. 필요한 물은 미리 준비해주세요.",
    createdAt: "2026-06-29T14:00:00Z",
    replies: 1,
    pinned: true,
  },
  {
    id: "p5",
    houseId: "h1",
    author: "토마스",
    category: "chat",
    title: "토요일 오전 클라이밍 함께 가실 분",
    body: "오전 10시쯤 볼더링장에 갈 예정입니다. 두 분 더 함께 갈 수 있어요.",
    createdAt: "2026-07-02T08:15:00Z",
    replies: 5,
    pinned: false,
  },
];
