import type { House, Resident, Post } from "./types";

// ── Houses ──────────────────────────────────────────────────────────
export const houses: House[] = [
  {
    id: "h1",
    name: "Seongsu Loom",
    city: "Seoul",
    neighborhood: "Seongsu-dong",
    region: "Seongsu-dong",
    lat: 37.5446,
    lng: 127.0559,
    monthlyRent: 780000,
    deposit: 3000000,
    cleaningFee: 80000,
    maintenanceFee: 40000,
    roomType: "one_room",
    bedrooms: 6,
    residents: 5,
    capacity: 6,
    amenities: ["Rooftop", "Coworking room", "Laundry", "Fiber wifi", "Weekly cleaning"],
    vibe: ["creative", "social"],
    rating: 4.9,
    reviews: 132,
    color: "#FF7A5C",
    photo: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&auto=format&fit=crop",
    blurb: "A converted textile workshop where the shared studio never really closes.",
    availableFrom: "2026-07-15",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h2",
    name: "Yeonnam Quiet House",
    city: "Seoul",
    neighborhood: "Yeonnam-dong",
    region: "Yeonnam-dong",
    lat: 37.5636,
    lng: 126.9256,
    monthlyRent: 690000,
    deposit: 2500000,
    cleaningFee: 70000,
    maintenanceFee: 70000,
    roomType: "one_room",
    bedrooms: 5,
    residents: 4,
    capacity: 5,
    amenities: ["Garden", "Reading nook", "Laundry", "Fiber wifi", "Bike storage"],
    vibe: ["quiet", "calm"],
    rating: 4.8,
    reviews: 96,
    color: "#00A699",
    photo: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&auto=format&fit=crop",
    blurb: "Low ceilings, tall bookshelves, and a house rule of gentle voices after ten.",
    availableFrom: "2026-08-01",
    minStayMonths: 6,
    genderPolicy: "female_only",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h3",
    name: "Mangwon River Studios",
    city: "Seoul",
    neighborhood: "Mangwon-dong",
    region: "Mangwon-dong",
    lat: 37.5559,
    lng: 126.9016,
    monthlyRent: 950000,
    deposit: 4000000,
    cleaningFee: 100000,
    maintenanceFee: 50000,
    roomType: "apartment",
    bedrooms: 8,
    residents: 6,
    capacity: 8,
    amenities: ["Ensuite", "Gym", "Rooftop", "Fiber wifi", "Parcel locker"],
    vibe: ["independent", "social"],
    rating: 4.7,
    reviews: 210,
    color: "#3E9BC4",
    photo: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    blurb: "Private studios that open onto a shared kitchen two minutes from the Han.",
    availableFrom: "2026-07-08",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h4",
    name: "Haebangchon Terrace",
    city: "Seoul",
    neighborhood: "Yongsan-gu",
    region: "Yongsan-gu",
    lat: 37.5405,
    lng: 126.9895,
    monthlyRent: 620000,
    deposit: 2000000,
    cleaningFee: 60000,
    maintenanceFee: 70000,
    roomType: "share_room",
    bedrooms: 4,
    residents: 6,
    capacity: 8,
    amenities: ["Terrace", "Communal dinners", "Laundry", "Fiber wifi"],
    vibe: ["social", "international"],
    rating: 4.6,
    reviews: 178,
    color: "#FF5A5F",
    photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&auto=format&fit=crop",
    blurb: "Twice-weekly rooftop dinners and a resident mix from nine countries.",
    availableFrom: "2026-07-20",
    minStayMonths: 2,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: true,
    parking: false,
  },
  {
    id: "h5",
    name: " Hongdae Maker House",
    city: "Seoul",
    neighborhood: "Seogyo-dong",
    region: "Seogyo-dong",
    lat: 37.5546,
    lng: 126.9226,
    monthlyRent: 720000,
    deposit: 2800000,
    cleaningFee: 70000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 6,
    residents: 6,
    capacity: 6,
    amenities: ["Workshop", "3D printers", "Coworking room", "Fiber wifi", "Laundry"],
    vibe: ["creative", "focused"],
    rating: 4.8,
    reviews: 145,
    color: "#7C6FE0",
    photo: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop",
    blurb: "A ground-floor workshop shared by furniture makers, coders, and one luthier.",
    availableFrom: "2026-09-01",
    minStayMonths: 6,
    genderPolicy: "male_only",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h7",
    name: "Seocho Commuter House",
    city: "Seoul",
    neighborhood: "Seocho-gu",
    region: "Seocho-gu",
    lat: 37.4837,
    lng: 127.0324,
    monthlyRent: 880000,
    deposit: 3500000,
    cleaningFee: 90000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 6,
    residents: 5,
    capacity: 6,
    amenities: ["Coworking room", "Gym", "Laundry", "Fiber wifi", "Parcel locker"],
    vibe: ["quiet", "focused"],
    rating: 4.7,
    reviews: 74,
    color: "#4A8FD6",
    photo: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80&auto=format&fit=crop",
    blurb: "One stop from Gangnam Station, built for people who value the extra hour of sleep.",
    availableFrom: "2026-07-18",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h8",
    name: "Pangyo Valley House",
    city: "Seongnam",
    neighborhood: "Bundang-gu",
    region: "Bundang-gu",
    lat: 37.3925,
    lng: 127.1180,
    monthlyRent: 810000,
    deposit: 3000000,
    cleaningFee: 80000,
    maintenanceFee: 40000,
    roomType: "apartment",
    bedrooms: 7,
    residents: 6,
    capacity: 7,
    amenities: ["Ensuite", "Coworking room", "Gym", "Fiber wifi", "Weekly cleaning"],
    vibe: ["focused", "social"],
    rating: 4.8,
    reviews: 61,
    color: "#2FB39C",
    photo: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80&auto=format&fit=crop",
    blurb: "A ten-minute walk to the tech valley, full of engineers who keep odd hours.",
    availableFrom: "2026-08-05",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: true,
    parking: true,
  },
  {
    id: "h6",
    name: "Ttukseom Sunrise",
    city: "Seoul",
    neighborhood: "Seongdong-gu",
    region: "Seongdong-gu",
    lat: 37.5310,
    lng: 127.0668,
    monthlyRent: 840000,
    deposit: 3200000,
    cleaningFee: 80000,
    maintenanceFee: 40000,
    roomType: "one_room",
    bedrooms: 7,
    residents: 5,
    capacity: 7,
    amenities: ["River view", "Yoga room", "Rooftop", "Fiber wifi", "Weekly cleaning"],
    vibe: ["calm", "wellness"],
    rating: 4.9,
    reviews: 88,
    color: "#FFB400",
    photo: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80&auto=format&fit=crop",
    blurb: "6am rooftop yoga optional, sunrise over the river included.",
    availableFrom: "2026-08-12",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h9",
    name: "Studio House",
    city: "Seoul",
    neighborhood: "Seongdong-gu",
    region: "Seongdong-gu",
    lat: 37.5364,
    lng: 127.0655,
    monthlyRent: 600000,
    deposit: 2600000,
    cleaningFee: 60000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 5,
    residents: 3,
    capacity: 4,
    amenities: ['Rooftop', 'Parcel locker', 'Fiber wifi', 'Workshop', 'Coworking room', 'Garden'],
    vibe: ['focused', 'quiet'],
    rating: 4.5,
    reviews: 181,
    color: "#3AA6B9",
    photo: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-07-08",
    minStayMonths: 6,
    genderPolicy: "male_only",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h10",
    name: "Cedar Flat",
    city: "Seoul",
    neighborhood: "Seongsu-dong",
    region: "Seongsu-dong",
    lat: 37.5453,
    lng: 127.0515,
    monthlyRent: 650000,
    deposit: 2500000,
    cleaningFee: 60000,
    maintenanceFee: 50000,
    roomType: "apartment",
    bedrooms: 5,
    residents: 4,
    capacity: 8,
    amenities: ['Reading nook', 'Laundry', 'Coworking room', 'Ensuite', 'Fiber wifi', 'Gym'],
    vibe: ['social', 'wellness'],
    rating: 4.8,
    reviews: 184,
    color: "#FF7A5C",
    photo: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-11-14",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h11",
    name: "Studio House",
    city: "Seoul",
    neighborhood: "Hongdae",
    region: "Hongdae",
    lat: 37.5530,
    lng: 126.9270,
    monthlyRent: 920000,
    deposit: 3300000,
    cleaningFee: 90000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 6,
    residents: 4,
    capacity: 7,
    amenities: ['Bike storage', 'Weekly cleaning', 'Ensuite', 'Coworking room', 'Reading nook', 'Garden'],
    vibe: ['creative', 'focused'],
    rating: 4.6,
    reviews: 165,
    color: "#00A699",
    photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-07-25",
    minStayMonths: 6,
    genderPolicy: "male_only",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h12",
    name: "Commons Rooms",
    city: "Seoul",
    neighborhood: "Gangnam-gu",
    region: "Gangnam-gu",
    lat: 37.5172,
    lng: 127.0509,
    monthlyRent: 610000,
    deposit: 2700000,
    cleaningFee: 60000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 7,
    residents: 7,
    capacity: 7,
    amenities: ['Coworking room', 'Rooftop', 'Weekly cleaning', 'Ensuite', 'Bike storage', 'Reading nook'],
    vibe: ['focused', 'international'],
    rating: 4.6,
    reviews: 158,
    color: "#3E9BC4",
    photo: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-07-16",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h13",
    name: "Nest Flat",
    city: "Seoul",
    neighborhood: "Seocho-gu",
    region: "Seocho-gu",
    lat: 37.4887,
    lng: 127.0324,
    monthlyRent: 840000,
    deposit: 3100000,
    cleaningFee: 80000,
    maintenanceFee: 50000,
    roomType: "share_room",
    bedrooms: 8,
    residents: 3,
    capacity: 6,
    amenities: ['Parcel locker', 'Weekly cleaning', 'Garden', 'Gym', 'Reading nook'],
    vibe: ['calm', 'social'],
    rating: 4.4,
    reviews: 78,
    color: "#FF5A5F",
    photo: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-10-27",
    minStayMonths: 2,
    genderPolicy: "male_only",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h14",
    name: "Haven House",
    city: "Seoul",
    neighborhood: "Seongdong-gu",
    region: "Seongdong-gu",
    lat: 37.5323,
    lng: 127.0646,
    monthlyRent: 1000000,
    deposit: 4300000,
    cleaningFee: 100000,
    maintenanceFee: 50000,
    roomType: "share_room",
    bedrooms: 4,
    residents: 7,
    capacity: 8,
    amenities: ['Yoga room', 'Rooftop', 'Bike storage', 'Parcel locker', 'Garden', 'Ensuite'],
    vibe: ['focused', 'calm'],
    rating: 4.5,
    reviews: 202,
    color: "#7C6FE0",
    photo: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-07-07",
    minStayMonths: 2,
    genderPolicy: "female_only",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h15",
    name: "Bloom Home",
    city: "Seoul",
    neighborhood: "Gangnam-gu",
    region: "Gangnam-gu",
    lat: 37.5130,
    lng: 127.0425,
    monthlyRent: 950000,
    deposit: 3100000,
    cleaningFee: 100000,
    maintenanceFee: 60000,
    roomType: "whole_house",
    bedrooms: 5,
    residents: 5,
    capacity: 5,
    amenities: ['Reading nook', 'Weekly cleaning', 'Gym', 'Ensuite'],
    vibe: ['international', 'calm'],
    rating: 4.5,
    reviews: 164,
    color: "#FFB400",
    photo: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-09-03",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h16",
    name: "Atelier Flat",
    city: "Seoul",
    neighborhood: "Mapo-gu",
    region: "Mapo-gu",
    lat: 37.5606,
    lng: 126.9073,
    monthlyRent: 650000,
    deposit: 2700000,
    cleaningFee: 60000,
    maintenanceFee: 40000,
    roomType: "whole_house",
    bedrooms: 8,
    residents: 4,
    capacity: 4,
    amenities: ['Reading nook', 'Coworking room', 'Weekly cleaning', 'Parcel locker', 'Gym'],
    vibe: ['creative', 'independent'],
    rating: 4.8,
    reviews: 176,
    color: "#4A8FD6",
    photo: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-08-26",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h17",
    name: "Atelier Flat",
    city: "Seoul",
    neighborhood: "Bundang-gu",
    region: "Bundang-gu",
    lat: 37.3908,
    lng: 127.1123,
    monthlyRent: 730000,
    deposit: 2800000,
    cleaningFee: 70000,
    maintenanceFee: 60000,
    roomType: "one_room",
    bedrooms: 4,
    residents: 4,
    capacity: 5,
    amenities: ['Workshop', 'Yoga room', 'Gym', 'Reading nook', 'Coworking room'],
    vibe: ['calm', 'quiet'],
    rating: 4.5,
    reviews: 90,
    color: "#2FB39C",
    photo: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-11-20",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h18",
    name: "Maple Rooms",
    city: "Seoul",
    neighborhood: "Itaewon",
    region: "Itaewon",
    lat: 37.5363,
    lng: 126.9995,
    monthlyRent: 860000,
    deposit: 3700000,
    cleaningFee: 90000,
    maintenanceFee: 60000,
    roomType: "share_room",
    bedrooms: 6,
    residents: 7,
    capacity: 7,
    amenities: ['Coworking room', 'Yoga room', 'Garden', 'Bike storage', 'Reading nook'],
    vibe: ['social', 'international'],
    rating: 4.5,
    reviews: 72,
    color: "#E8654F",
    photo: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-10-26",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h19",
    name: "Atelier Co-living",
    city: "Seoul",
    neighborhood: "Mangwon-dong",
    region: "Mangwon-dong",
    lat: 37.5565,
    lng: 126.8972,
    monthlyRent: 1020000,
    deposit: 4100000,
    cleaningFee: 100000,
    maintenanceFee: 70000,
    roomType: "one_room",
    bedrooms: 8,
    residents: 7,
    capacity: 8,
    amenities: ['Garden', 'Fiber wifi', 'Yoga room', 'Rooftop'],
    vibe: ['wellness', 'social'],
    rating: 4.6,
    reviews: 101,
    color: "#3AA6B9",
    photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-10-27",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h20",
    name: "Harbor House",
    city: "Seoul",
    neighborhood: "Itaewon",
    region: "Itaewon",
    lat: 37.5393,
    lng: 126.9936,
    monthlyRent: 900000,
    deposit: 3100000,
    cleaningFee: 90000,
    maintenanceFee: 40000,
    roomType: "share_room",
    bedrooms: 4,
    residents: 2,
    capacity: 8,
    amenities: ['Workshop', 'Laundry', 'Ensuite', 'Rooftop', 'Yoga room'],
    vibe: ['creative', 'social'],
    rating: 4.7,
    reviews: 225,
    color: "#FF7A5C",
    photo: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-11-17",
    minStayMonths: 3,
    genderPolicy: "male_only",
    petsAllowed: false,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h21",
    name: "Quarter Flat",
    city: "Seoul",
    neighborhood: "Yongsan-gu",
    region: "Yongsan-gu",
    lat: 37.5368,
    lng: 126.9840,
    monthlyRent: 880000,
    deposit: 3300000,
    cleaningFee: 90000,
    maintenanceFee: 70000,
    roomType: "one_room",
    bedrooms: 7,
    residents: 2,
    capacity: 4,
    amenities: ['Gym', 'Ensuite', 'Parcel locker', 'Yoga room', 'Reading nook'],
    vibe: ['calm', 'international'],
    rating: 4.6,
    reviews: 170,
    color: "#00A699",
    photo: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-11-09",
    minStayMonths: 6,
    genderPolicy: "male_only",
    petsAllowed: false,
    smokingAllowed: true,
    parking: true,
  },
  {
    id: "h22",
    name: "Nest Residence",
    city: "Seoul",
    neighborhood: "Yeonnam-dong",
    region: "Yeonnam-dong",
    lat: 37.5623,
    lng: 126.9234,
    monthlyRent: 830000,
    deposit: 2700000,
    cleaningFee: 80000,
    maintenanceFee: 50000,
    roomType: "share_room",
    bedrooms: 6,
    residents: 6,
    capacity: 9,
    amenities: ['Workshop', 'Laundry', 'Reading nook', 'Gym'],
    vibe: ['creative', 'independent'],
    rating: 4.9,
    reviews: 159,
    color: "#3E9BC4",
    photo: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-10-06",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h23",
    name: "Willow Co-living",
    city: "Seoul",
    neighborhood: "Seocho-gu",
    region: "Seocho-gu",
    lat: 37.4800,
    lng: 127.0302,
    monthlyRent: 570000,
    deposit: 2100000,
    cleaningFee: 60000,
    maintenanceFee: 50000,
    roomType: "whole_house",
    bedrooms: 6,
    residents: 5,
    capacity: 7,
    amenities: ['Rooftop', 'Garden', 'Gym', 'Parcel locker', 'Weekly cleaning', 'Coworking room'],
    vibe: ['social', 'focused'],
    rating: 4.5,
    reviews: 66,
    color: "#FF5A5F",
    photo: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-07-25",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: true,
    parking: true,
  },
  {
    id: "h24",
    name: "Willow Co-living",
    city: "Seoul",
    neighborhood: "Seocho-gu",
    region: "Seocho-gu",
    lat: 37.4795,
    lng: 127.0374,
    monthlyRent: 1000000,
    deposit: 3600000,
    cleaningFee: 100000,
    maintenanceFee: 40000,
    roomType: "apartment",
    bedrooms: 8,
    residents: 2,
    capacity: 6,
    amenities: ['Laundry', 'Garden', 'Coworking room', 'Weekly cleaning', 'Rooftop', 'Reading nook'],
    vibe: ['wellness', 'quiet'],
    rating: 4.7,
    reviews: 96,
    color: "#7C6FE0",
    photo: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-10-01",
    minStayMonths: 2,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h25",
    name: "Commons House",
    city: "Seoul",
    neighborhood: "Mangwon-dong",
    region: "Mangwon-dong",
    lat: 37.5504,
    lng: 126.9041,
    monthlyRent: 660000,
    deposit: 2300000,
    cleaningFee: 70000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 7,
    residents: 3,
    capacity: 5,
    amenities: ['Reading nook', 'Weekly cleaning', 'Parcel locker', 'Fiber wifi', 'Yoga room'],
    vibe: ['independent', 'wellness'],
    rating: 4.8,
    reviews: 109,
    color: "#FFB400",
    photo: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-07-01",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h26",
    name: "Sunroom House",
    city: "Seoul",
    neighborhood: "Yongsan-gu",
    region: "Yongsan-gu",
    lat: 37.5457,
    lng: 126.9848,
    monthlyRent: 980000,
    deposit: 3800000,
    cleaningFee: 100000,
    maintenanceFee: 50000,
    roomType: "apartment",
    bedrooms: 8,
    residents: 6,
    capacity: 7,
    amenities: ['Yoga room', 'Fiber wifi', 'Workshop', 'Gym', 'Reading nook'],
    vibe: ['creative', 'calm'],
    rating: 4.9,
    reviews: 53,
    color: "#4A8FD6",
    photo: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-09-14",
    minStayMonths: 2,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h27",
    name: "Loft Place",
    city: "Seoul",
    neighborhood: "Jongno-gu",
    region: "Jongno-gu",
    lat: 37.5786,
    lng: 126.9806,
    monthlyRent: 580000,
    deposit: 2200000,
    cleaningFee: 60000,
    maintenanceFee: 40000,
    roomType: "whole_house",
    bedrooms: 5,
    residents: 4,
    capacity: 5,
    amenities: ['Rooftop', 'Weekly cleaning', 'Gym', 'Reading nook', 'Parcel locker'],
    vibe: ['international', 'social'],
    rating: 4.4,
    reviews: 119,
    color: "#2FB39C",
    photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-07-11",
    minStayMonths: 2,
    genderPolicy: "female_only",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h28",
    name: "Haven Place",
    city: "Seoul",
    neighborhood: "Mapo-gu",
    region: "Mapo-gu",
    lat: 37.5696,
    lng: 126.8970,
    monthlyRent: 650000,
    deposit: 2400000,
    cleaningFee: 60000,
    maintenanceFee: 40000,
    roomType: "one_room",
    bedrooms: 8,
    residents: 3,
    capacity: 4,
    amenities: ['Weekly cleaning', 'Workshop', 'Reading nook', 'Fiber wifi'],
    vibe: ['social', 'wellness'],
    rating: 4.9,
    reviews: 79,
    color: "#E8654F",
    photo: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-10-05",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h29",
    name: "Commons Residence",
    city: "Seoul",
    neighborhood: "Jongno-gu",
    region: "Jongno-gu",
    lat: 37.5721,
    lng: 126.9818,
    monthlyRent: 890000,
    deposit: 3700000,
    cleaningFee: 90000,
    maintenanceFee: 50000,
    roomType: "share_room",
    bedrooms: 7,
    residents: 8,
    capacity: 8,
    amenities: ['Reading nook', 'Ensuite', 'Workshop', 'Fiber wifi'],
    vibe: ['social', 'quiet'],
    rating: 4.4,
    reviews: 203,
    color: "#3AA6B9",
    photo: "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-10-18",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h30",
    name: "Quarter Studios",
    city: "Seoul",
    neighborhood: "Seogyo-dong",
    region: "Seogyo-dong",
    lat: 37.5486,
    lng: 126.9262,
    monthlyRent: 980000,
    deposit: 3800000,
    cleaningFee: 100000,
    maintenanceFee: 70000,
    roomType: "one_room",
    bedrooms: 4,
    residents: 9,
    capacity: 9,
    amenities: ['Workshop', 'Coworking room', 'Weekly cleaning', 'Fiber wifi', 'Ensuite'],
    vibe: ['calm', 'international'],
    rating: 4.8,
    reviews: 157,
    color: "#FF7A5C",
    photo: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-10-22",
    minStayMonths: 2,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: false,
  },
  {
    id: "h31",
    name: "Garden Home",
    city: "Seoul",
    neighborhood: "Gangnam-gu",
    region: "Gangnam-gu",
    lat: 37.5130,
    lng: 127.0443,
    monthlyRent: 950000,
    deposit: 3700000,
    cleaningFee: 100000,
    maintenanceFee: 60000,
    roomType: "whole_house",
    bedrooms: 4,
    residents: 3,
    capacity: 4,
    amenities: ['Bike storage', 'Weekly cleaning', 'Reading nook', 'Coworking room'],
    vibe: ['calm', 'international'],
    rating: 4.7,
    reviews: 221,
    color: "#00A699",
    photo: "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-10-25",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h32",
    name: "Quarter Home",
    city: "Seoul",
    neighborhood: "Bundang-gu",
    region: "Bundang-gu",
    lat: 37.3867,
    lng: 127.1175,
    monthlyRent: 730000,
    deposit: 2700000,
    cleaningFee: 70000,
    maintenanceFee: 50000,
    roomType: "apartment",
    bedrooms: 5,
    residents: 2,
    capacity: 5,
    amenities: ['Coworking room', 'Laundry', 'Parcel locker', 'Weekly cleaning', 'Gym', 'Yoga room'],
    vibe: ['wellness', 'quiet'],
    rating: 4.8,
    reviews: 99,
    color: "#3E9BC4",
    photo: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-07-06",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h33",
    name: "Willow Place",
    city: "Seoul",
    neighborhood: "Seocho-gu",
    region: "Seocho-gu",
    lat: 37.4818,
    lng: 127.0302,
    monthlyRent: 560000,
    deposit: 2000000,
    cleaningFee: 60000,
    maintenanceFee: 40000,
    roomType: "whole_house",
    bedrooms: 5,
    residents: 5,
    capacity: 6,
    amenities: ['Fiber wifi', 'Yoga room', 'Rooftop', 'Weekly cleaning'],
    vibe: ['wellness', 'creative'],
    rating: 4.4,
    reviews: 139,
    color: "#FF5A5F",
    photo: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-09-28",
    minStayMonths: 3,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: true,
    parking: false,
  },
  {
    id: "h34",
    name: "Garden Home",
    city: "Seoul",
    neighborhood: "Yongsan-gu",
    region: "Yongsan-gu",
    lat: 37.5462,
    lng: 126.9887,
    monthlyRent: 680000,
    deposit: 2900000,
    cleaningFee: 70000,
    maintenanceFee: 70000,
    roomType: "whole_house",
    bedrooms: 6,
    residents: 2,
    capacity: 7,
    amenities: ['Garden', 'Parcel locker', 'Yoga room', 'Fiber wifi', 'Coworking room', 'Rooftop'],
    vibe: ['focused', 'calm'],
    rating: 4.7,
    reviews: 75,
    color: "#7C6FE0",
    photo: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-11-05",
    minStayMonths: 2,
    genderPolicy: "any",
    petsAllowed: false,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h35",
    name: "Studio Rooms",
    city: "Seoul",
    neighborhood: "Seocho-gu",
    region: "Seocho-gu",
    lat: 37.4856,
    lng: 127.0300,
    monthlyRent: 630000,
    deposit: 2200000,
    cleaningFee: 60000,
    maintenanceFee: 50000,
    roomType: "apartment",
    bedrooms: 6,
    residents: 2,
    capacity: 5,
    amenities: ['Parcel locker', 'Bike storage', 'Workshop', 'Fiber wifi'],
    vibe: ['independent', 'creative'],
    rating: 4.9,
    reviews: 155,
    color: "#FFB400",
    photo: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-08-08",
    minStayMonths: 6,
    genderPolicy: "any",
    petsAllowed: true,
    smokingAllowed: false,
    parking: true,
  },
  {
    id: "h36",
    name: "Sunroom Flat",
    city: "Seoul",
    neighborhood: "Seogyo-dong",
    region: "Seogyo-dong",
    lat: 37.5583,
    lng: 126.9190,
    monthlyRent: 1030000,
    deposit: 4500000,
    cleaningFee: 100000,
    maintenanceFee: 50000,
    roomType: "one_room",
    bedrooms: 4,
    residents: 5,
    capacity: 7,
    amenities: ['Parcel locker', 'Fiber wifi', 'Garden', 'Weekly cleaning', 'Gym', 'Rooftop'],
    vibe: ['independent', 'creative'],
    rating: 4.7,
    reviews: 132,
    color: "#4A8FD6",
    photo: "https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80&auto=format&fit=crop",
    blurb: "A comfortable co-living home with a friendly house culture and easy access to transit.",
    availableFrom: "2026-09-08",
    minStayMonths: 2,
    genderPolicy: "female_only",
    petsAllowed: true,
    smokingAllowed: false,
    parking: false,
  }
];

// ── Residents (used for matching) ───────────────────────────────────
export const residents: Resident[] = [
  {
    id: "r1",
    name: "Jae",
    age: 27,
    occupation: "UX Designer",
    bio: "Early riser, keeps a tidy desk, loves a quiet Sunday.",
    sleepSchedule: "early",
    cleanliness: 5,
    social: 3,
    interests: ["design", "coffee", "hiking", "film"],
    smoker: false,
    pets: false,
  },
  {
    id: "r2",
    name: "Mina",
    age: 24,
    occupation: "Illustrator",
    bio: "Night owl, always mid-project, will feed anyone's plants.",
    sleepSchedule: "night",
    cleanliness: 3,
    social: 5,
    interests: ["art", "music", "cooking", "film"],
    smoker: false,
    pets: true,
  },
  {
    id: "r3",
    name: "Tomas",
    age: 31,
    occupation: "Backend Engineer",
    bio: "Flexible hours, gym at odd times, quiet but friendly.",
    sleepSchedule: "flexible",
    cleanliness: 4,
    social: 2,
    interests: ["coding", "climbing", "coffee", "games"],
    smoker: false,
    pets: false,
  },
  {
    id: "r4",
    name: "Soo",
    age: 29,
    occupation: "Chef",
    bio: "Cooks big shared dinners, hums in the kitchen, up late.",
    sleepSchedule: "night",
    cleanliness: 4,
    social: 5,
    interests: ["cooking", "music", "travel", "wine"],
    smoker: false,
    pets: false,
  },
  {
    id: "r5",
    name: "Hana",
    age: 26,
    occupation: "PhD Student",
    bio: "Reads a lot, needs calm, joins the occasional board game night.",
    sleepSchedule: "early",
    cleanliness: 5,
    social: 2,
    interests: ["books", "hiking", "games", "coffee"],
    smoker: false,
    pets: false,
  },
  {
    id: "r6",
    name: "Diego",
    age: 33,
    occupation: "Product Manager",
    bio: "Social connector, hosts the house dinners, keeps the calendar.",
    sleepSchedule: "flexible",
    cleanliness: 3,
    social: 5,
    interests: ["travel", "music", "cooking", "sports"],
    smoker: false,
    pets: true,
  },
];

// ── Community posts ─────────────────────────────────────────────────
export const posts: Post[] = [
  {
    id: "p1",
    houseId: "h1",
    author: "Diego",
    category: "event",
    title: "Rooftop dinner this Friday, 8pm",
    body: "Bringing a big pot of curry. Bring a side or just yourself. Sign up on the fridge sheet.",
    createdAt: "2026-07-01T09:00:00Z",
    replies: 7,
    pinned: true,
  },
  {
    id: "p2",
    houseId: "h1",
    author: "Jae",
    category: "chore",
    title: "Kitchen deep-clean rotation for July",
    body: "Updated the rotation. Check who you're paired with. Let's keep the counters clear this month.",
    createdAt: "2026-07-01T11:30:00Z",
    replies: 3,
    pinned: false,
  },
  {
    id: "p3",
    houseId: "h1",
    author: "Mina",
    category: "market",
    title: "Free: desk lamp + two chairs",
    body: "Moving my studio around. First come. They're by the coworking room.",
    createdAt: "2026-06-30T18:20:00Z",
    replies: 2,
    pinned: false,
  },
  {
    id: "p4",
    houseId: "h1",
    author: "House Manager",
    category: "notice",
    title: "Water maintenance Tuesday 2–4pm",
    body: "Building water will be off for two hours Tuesday afternoon. Fill a bottle beforehand.",
    createdAt: "2026-06-29T14:00:00Z",
    replies: 1,
    pinned: true,
  },
  {
    id: "p5",
    houseId: "h1",
    author: "Tomas",
    category: "chat",
    title: "Anyone up for the Saturday morning climb?",
    body: "Heading to the bouldering gym around 10. Room for two more.",
    createdAt: "2026-07-02T08:15:00Z",
    replies: 5,
    pinned: false,
  },
];
